// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBM-pHMs-5T2E95ou-sRfQbK74y5ygIjt4',
    appId: '1:351151743403:web:46842ff448ffd92a3a32ee',
    messagingSenderId: '351151743403',
    projectId: 'pakain-aso1',
    authDomain: 'pakain-aso1.firebaseapp.com',
    storageBucket: 'pakain-aso1.appspot.com',
    measurementId: 'G-8V357MYBZ6',
    databaseURL:
        'https://pakain-aso1-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCAYZ04JrFQ87ILdKevYiBQ32Uop7pbKs',
    appId: '1:351151743403:android:6f18d096879b4d593a32ee',
    messagingSenderId: '351151743403',
    projectId: 'pakain-aso1',
    storageBucket: 'pakain-aso1.appspot.com',
    databaseURL:
        'https://pakain-aso1-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIi_JOLcuTyu4M_5FS4WvR7MKFNJOjNaE',
    appId: '1:351151743403:ios:280ad43eb662d49e3a32ee',
    messagingSenderId: '351151743403',
    projectId: 'pakain-aso1',
    storageBucket: 'pakain-aso1.appspot.com',
    iosBundleId: 'com.example.pakainAso',
    databaseURL:
        'https://pakain-aso1-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIi_JOLcuTyu4M_5FS4WvR7MKFNJOjNaE',
    appId: '1:351151743403:ios:679404e71de8d5803a32ee',
    messagingSenderId: '351151743403',
    projectId: 'pakain-aso1',
    storageBucket: 'pakain-aso1.appspot.com',
    iosBundleId: 'com.example.pakainAso.RunnerTests',
    databaseURL:
        'https://pakain-aso1-default-rtdb.asia-southeast1.firebasedatabase.app/',
  );
}
